container_workflow_tool/config/f30.yaml

Create config file for f30

---

Dockerfile.generator
Makefile
container_workflow_tool/config/f31.yaml
files/run.sh

This commit adds cwt generator used by https://github.com/sclorg/betka.
cwt-generator generates dist-git sources from upstream repositories.

Image generator for Fedora dist-git repos

---

Makefile
README.md

This updates Makefile with quay.io docker names.
Also, README.md is updated.

cwt available in quay.io/rhscl/cwt-generator

---

container_workflow_tool/config/default.yaml
container_workflow_tool/config/f31.yaml

This adds support for generation python3 sources for Fedora dist-git.

Add support for building python3

---

container_workflow_tool/config/default.yaml
container_workflow_tool/config/f31.yaml
container_workflow_tool/config/f32.yaml

The commit enables nginx and nodejs containers.
The versions are updated.

Enable nginx and nodejs sources

---

.pre-commit-config.yaml
container_workflow_tool/config/default.yaml
container_workflow_tool/config/f33.yaml

Update YAML configuration files for Fedora images

---

container_workflow_tool/config/default.yaml
container_workflow_tool/config/f32.yaml
container_workflow_tool/config/f33.yaml
container_workflow_tool/config/f34.yaml

This pull request allows creating Fedora downstream changes for
postgresql and mariadb containers.

Allow postgresql mariadb

---

Dockerfile.generator
Dockerfile.tests

Use fedora:rawhide from registry.fedoraproject.org

---

.travis.yml
Dockerfile.tests
Makefile
container_workflow_tool/distgit.py

Fix definitions
* _update_dockerfile_rebuild definition
* fix _get_from return value
* fix _set_from typo

Fix function definition and _set_from

---

.pre-commit-config.yaml
container_workflow_tool/cli_common.py
container_workflow_tool/main.py
container_workflow_tool/utility.py

Reverts sclorg/container-workflow-tool#30

Revert "Add possibility to log some functions into file"

---

Makefile

Update Makefile to use proper docker binary

---

container_workflow_tool/config/default.yaml
container_workflow_tool/config/f33.yaml
container_workflow_tool/config/f34.yaml

This pull request adds support for sync the rest our containers

Add support for the rest containers

---

setup.py

Hello,
the cwt's version in the setup.py script needs to be updated in order to create updated PyPI package.
This PR includes the version update in setup.py.

update the cwt version in the setup.py script

---

Makefile
container_workflow_tool/distgit.py
tests/data/test-openshift.yaml
tests/test_distgit.py

This commit adds support for CVP pipeline and update file `test/test-openshift.yaml` which is needed for CVP

Support for CVP pipeline

---

setup.py

Bump version to 1.2.0

---

container_workflow_tool/main.py

Get config before initialization

---

.github/workflows/pr-tests.yaml

Let's use Testing Farm for scheduling tests

---

container_workflow_tool/main.py
container_workflow_tool/utility.py

move config splitting into a separate function and use it when setting up config early

fix failure when config is not set

---

container_workflow_tool/distgit.py
tests/test_distgit.py

This pull request adds support for syncing RHEL9 images which updates test_openshift.yaml file

Let's add support also for RHEL9

---

setup.py

This pull request is blocked by #66 #65 

Bump version to 1.5.0

---

container_workflow_tool/distgit.py
setup.py
tests/data/test-openshift.yaml
tests/test_distgit.py

This fixes bug in case of TAG: \"TAG_VALUE\" is
defined

test_openshift.yaml has for like TAG: TAG_VALUE

---

setup.py

Bump  version before release v1.5.2

---

container_workflow_tool/config.py

This pull request only brings a support of Jira to configuration files.
The rest will be part of internal CWT.

Adds support Jira to configuration

---

Dockerfile.generator
Dockerfile.tests
setup.py

Bump version to 1.5.3

---

container_workflow_tool/main.py

git: fix not setting up tmp structure

---

.github/workflows/pr-tests.yaml

It updates GitHub Action and allows create issue_comment and github_summary.

Update pr-tests with comment and summary

---

.github/workflows/pr-tests.yaml

GitHub provides their own variables. Let's use them

Fix TMT variables
